/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2022 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/


const char html_page_reboot[] PROGMEM =
"<p>Rebooting... Refresh in <span id='count'>10s</span>...</p>"
;

const char html_page_reset[] PROGMEM =
"<p>Resetting... Connect to SSID _SSID_...</p>"
;


const char html_page_save_reboot[] PROGMEM =
"<p>Saving configuration and rebooting... Refresh in <span id='count'>10s</span>...</p>"
;

const char html_page_server[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; Server parameters &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>Server Url as http://IP:PORT/</b>"
                "<br/><br/>"
                "<input id='url' name='url' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_SERVER_URL_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_others[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; Others Parameters &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>Debug logs</b>"
                "<select name='DebugLogs'>"
                    "<option value='ON' _DEBUG_LOGS_ON_>On</option>"
                    "<option value='OFF' _DEBUG_LOGS_OFF_>Off</option>"
                "</select>"
            "</p>"
            "<p><b>Debug packets</b>"
                "<select name='DebugPckts'>"
                    "<option value='ON' _DEBUG_PCKTS_ON_>On</option>"
                    "<option value='OFF' _DEBUG_PCKTS_OFF_>Off</option>"
                "</select>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_status[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
    "<legend><b>&nbsp; Status &nbsp;</b></legend>"
    "<p><b>HVAC Status</b>"
        " ==> "
        "_HVAC_STATUS_"
    "</p>"
     "<p><b>HVAC Connection Retries</b>"
        " ==> "
        "_HVAC_RETRIES_"
    "</p>"
     "<p><b>WIFI RSSI</b>"
        " ==> "
        "_WIFI_STATUS_ dBm"
    "</p>"
     "<p><b>Free Heap</b>"
        " ==> "
        "_FREE_HEAP_"
    "</p>"
     "<p><b>Boot time</b>"
        " ==> "
        "_BOOT_TIME_"
    "</p>"
    "</fieldset>"
    "<br />"
    "<p>"
        "<a class='button back' href='/'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_wifi[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; WIFI Parameters &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>Hostname</b>"
                "<br/>"
                "<input id='hn' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                " name='hn' placeholder=' ' value='_UNIT_NAME_'>"
            "</p>"
            "<p><b>SSID</b>"
                "<br/>"
                "<input id='ssid' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "name='ssid' placeholder=' ' value='_SSID_'>"
            "</p>"
            "<p><b>PSK</b>"
                "<br/>"
                "<input id='psk' type='password' name='psk' placeholder=' ' value='_PSK_'>"
            "</p>"
            "<p><b>OTA Password</b>"
                "<br/>"
                "<input id='otapwd' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "name='otapwd' placeholder=' ' value='_OTA_PWD_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>Back</a>"
    "</p>"
"</div>"
;


const char html_page_control[] PROGMEM =
"<h2>Current temperature _ROOMTEMP_&#176;</h2>"
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; Control Unit &nbsp;</b></legend>"
        "<p style='display: inline;'><b> Temperature </b>(<span id='tempScale'>&#176;_TEMP_SCALE_</span>)"
            "<br/>"
            "<button onclick='setTemp(0)' class='temp bgrn' style='text-align:center;width:30px;margin-left: 5px;margin-right: 2px;'>-</button>"
            "<form id='FTEMP_' style='display:inline'>"
                "<input name='TEMP' id='TEMP' type='text' value='_TEMP_' style='text-align:center;width:60px;margin-left: 5px;margin-right: 2px;' />"
            "</form>"
            "<button onclick='setTemp(1)' class='temp bgrn' style='text-align:center;width:30px;margin-left: 5px;margin-right: 2px;'>+</button>"
        "</p>"
        "<p>"
            "<b>Power</b>"
            "<form onchange='this.submit()' method='POST'>"
                "<select name='POWER'>"
                    "<option value='ON' _POWER_ON_>On</option>"
                    "<option value='OFF' _POWER_OFF_>Off</option>"
                "</select>"
            "</form>"
        "</p>"
        "<p><b>Mode</b>"
            "<form onchange='this.submit()' method='POST'>"
                "<select name='MODE' id='MODE'>"
                    "<option value='AUTO' _MODE_A_>&#9851; Auto</option>"
                    "<option value='DRY' _MODE_D_>&#128167; Dry</option>"
                    "<option value='COOL' _MODE_C_>&#10052;&#65039; Cool</option>"
                    "<option value='HEAT' _MODE_H_>&#9728;&#65039; Heat</option>"
                    "<option value='FAN' _MODE_F_>&#10051; Fan</option>"
                "</select>"
            "</form>"
        "</p>"
        "<p><b>Fan</b>"
            "<form onchange='this.submit()' method='POST'>"
                "<select name='FAN'>"
                    "<option value='AUTO' _FAN_A_>&#9851; Auto</option>"
                    "<option value='QUIET' _FAN_Q_>.... Quiet</option>"
                    "<option value='1' _FAN_1_>...: Speed 1</option>"
                    "<option value='2' _FAN_2_>..:: Speed 2</option>"
                    "<option value='3' _FAN_3_>.::: Speed 3</option>"
                    "<option value='4' _FAN_4_>:::: Speed 4</option>"
                "</select>"
            "</form>"
        "</p>"
        "<p><b>Vane</b>"
            "<form onchange='this.submit()' method='POST'>"
                "<select name='VANE'>"
                    "<option value='AUTO' _VANE_A_>&#9851; Auto</option>"
                    "<option value='SWING' _VANE_S_>&#9887; Swing</option>"
                    "<option value='1' _VANE_1_>&#10143; Position 1</option>"
                    "<option value='2' _VANE_2_>&#10143; Position 2</option>"
                    "<option value='3' _VANE_3_>&#10143; Position 3</option>"
                    "<option value='4' _VANE_4_>&#10143; Position 4</option>"
                    "<option value='5' _VANE_5_>&#10143; Position 5</option>"
                "</select>"
            "</form>"
        "</p>"
        "<p><b>Wide Vanne</b>"
            "<form onchange='this.submit()' method='POST'>"
                "<select name='WIDEVANE'>"
                    "<option value='SWING' _WVANE_S_>&#9887; Swing</option>"
                    "<option value='<<' _WVANE_1_><< Position 1</option>"
                    "<option value='<' _WVANE_2_>< Position 2</option>"
                    "<option value='|' _WVANE_3_>| Position 3</option>"
                    "<option value='>' _WVANE_4_>> Position 4</option>"
                    "<option value='>>' _WVANE_5_>>> Position 5</option>"
                    "<option value='<>' _WVANE_6_><> Position 6</option>"
                "</select>"
            "</form>"
        "</p>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/'>Back</a>"
    "</p>"
"</div>"
"<script>"
"const queryParams = (window.location.search.split('?')[1] || '')"
        ".split('&')"
        ".reduce((QS, current) => {"
            "const [key, value] = current.split('=');"
            "return Object.assign(QS, {[key]: value !== undefined ? value : ''});"
        "}, {});"

"function setTemp(b) {"
    "var t = document.getElementById('TEMP');"
    "if (b && t.value < _MAX_TEMP_) {"
        "t.value = Number(t.value) + _TEMP_STEP_;"
    "} else if (!b && t.value > _MIN_TEMP_) {"
        "t.value = Number(t.value) - _TEMP_STEP_;"
    "}"
    "document.getElementById('FTEMP_').submit();"
"}"

"if (queryParams['TEMP']) {"
    "document.getElementById('TEMP').value = queryParams['TEMP'];"
"}"

"if (!_HEAT_MODE_SUPPORT_) {"
    "var options = document.getElementById('MODE').options;"
    "options[3].disabled = (options[3].value == 'HEAT');"
"}"
"</script>"
;

const char html_page_unit[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; Unit configuration &nbsp;</b></legend>"
        "<form method='post'>"
            "<p>"
                "<b>Temperature unit</b>"
                "<select name='tu'>"
                    "<option value='cel' _TU_CEL_>Celcius</option>"
                    "<option value='fah' _TU_FAH_>Fahrenheit</option>"
                "</select>"
            "</p>"
            "<p><b>Minimum temperature</b>"
                "<br/>"
                "<input type='number' id='min_temp' name='min_temp' placeholder=' ' value='_MIN_TEMP_'>"
            "</p>"
            "<p><b>Maximum temperature</b>"
                "<br/>"
                "<input type='number' id='max_temp' name='max_temp' placeholder=' ' value='_MAX_TEMP_'>"
            "</p>"
            "<p><b>Temperature step</b>"
                "<br/>"
                "<input type='number' id='temp_step' step='0.1' name='temp_step' placeholder=' ' value='_TEMP_STEP_'>"
            "</p>"
            "<p>"
                "<b>Mode support</b>"
                "<select name='md'>"
                    "<option value='all' _MD_ALL_>All modes</option>"
                    "<option value='nht' _MD_NONHEAT_>All modes except heat</option>"
                "</select>"
            "</p>"
            "<p><b>Web password</b>"
                "<br/>"
                "<input id='lpw' name='lpw' type='password' placeholder=' ' value='_LOGIN_PASSWORD_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>Save & Reboot</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button' href='/setup' class='back'>Back</a>"
    "</p>"
"</div>"
;

const char html_page_login[] PROGMEM =
"<script>"
    "var loginSucess = _LOGIN_SUCCESS_;"
    "document.onreadystatechange = function() {"
        "if (document.readyState === 'complete') {"
            "if (loginSucess == 1) {"
                "var element = document.getElementById('login_form');"
                "element.parentNode.removeChild(element);"
            "}"
        "}"
    "}"
"</script>"
"<div id='login_form' name='login_form'>"
    "<fieldset>"
        "<legend><b>&nbsp; Authentication &nbsp;</b></legend>"
        "<form action='/login' method='post'>"
            "<!--<p>To log in, enter user: <b>admin</b> and password</p>"
            "<p><b>User</b>-->"
                "<input type='hidden' name='USERNAME' placeholder='user name' value='admin'>"
            "</p>"
            "<p><b>Password</b>"
                "<input type='password' name='PASSWORD' placeholder='Password'>"
            "</p>"
            "<br/>"
            "<button name='SUBMIT' type='submit' class='button bgrn'>Login</button>"
        "</form>"
        "<!-- <br> You can go to <a href='/status'>status page</a>-->"
        "<br>"
    "</fieldset>"
"</div>"
"<div>"
    "_LOGIN_MSG_"
"</div>"
;

const char html_page_upgrade[] PROGMEM =
"<script>"
    "function eb(s) {"
        "return document.getElementById(s);"
    "}"
"</script>"
    "<div id='f1' style='display:block;'>"
        "<fieldset>"
            "<legend><b>&nbsp; Upgrade &nbsp;</b></legend>"
            "<form method='post' action='upload' enctype='multipart/form-data'>"
                "<p><span>Firmware OTA upgrade by bin file upload</span></p>"
                "<br>"
                "<input type='file' accept='.bin' name='upload'>"
                "<br>"
                "<br>"
                "<button type='submit' onclick=\"eb('f1').style.display='none';eb('f2').style.display='block';this.form.submit();\" class='button bgrn'>Start upgrade</button>"
            "</form>"
        "</fieldset>"
        "<p>"
            "<a class='button back' href='/'>Back</a>"
        "</p>"
    "</div>"
    "<div id='f2' style='display:none;text-align:center;'><b>Upload started ...</b></div>"
;


const char html_page_upload[] PROGMEM =
"<div id='l1' name='l1'>"
    "<br>_UPLOAD_MSG_"
    "<p>"
        "<a class='button back' href='/upgrade'>Back</a>"
    "</p>"
"</div>"
;
